[package]
name = "ipblckr"
version = "0.1.0"
authors = ["Joao Martins <mdj@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pickledb = "0.4.1"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"